### ISSUE TITLE
Travis CI Free deprecation

### ISSUE THREAD

**Issue by hymccord** [tsitu/MH-Tools#227]
Travis CI deprecated their free tier of building even for open source projects. They migrated all non-paid users to a trial plan with 10,000 credits (about 1000 minutes of build time) after which you have to ask for more OSS credits via support.

Do you feel that migrating from travis to github-actions is needed?  
I have been building my personal branches with actions for a little while. You can see my workflow [here](https://github.com/hymccord/MH-Tools/blob/1ec3dc0723d0a621491909f853403b3550a321b2/.github/workflows/publish.yml).  
I can submit a PR of this file if OK'd!

**Comment by DevJackSmith** [comment]
Another option is circleci. Also limited but might be enough.

**Comment by tsitu** [comment]
Hey Hank, yeah this is actually something I was thinking of doing a couple of years back.

Travis has been working fine up to this point, presumably because we're not using a ton of build time. However I do agree that a migration to GitHub Actions is safer in the long run.

I'd like to keep a record of build history on Travis if possible though, do you know if migrating out will delete that? Also haven't looked deeply enough into GHA to know if we can get 100% feature parity. To be fair, all we're doing is a few simple Node scripts so I'm assuming it'll be kosher.
