### ISSUE TITLE
Setup Tool: Cheese in URL Params

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#38]
Cheese does not get populated correctly from the URL:
[Ganwnia Rift - Riftagio](https://tsitu.github.io/MH-Tools/setup.html?location=Gnawnia%20Rift&cheese=Riftiago )
[Furoma Rift -Rift Susheese](https://tsitu.github.io/MH-Tools/setup.html?location=Furoma%20Rift&phase=Pagoda&cheese=Rift%20Susheese&battery=6 )

This seems to only affect the setup tool not the CRE

**Comment by Babalela01** [comment]
Icwberg Sublocations also do not load from url correctly : http://tsitu.github.io/MH-Tools/setup.html?location=Iceberg&phase=The%20Mad%20Depths%20(Hearthstone)&cheese=SB+

**Comment by tsitu** [comment]
@Babalela01 
Both bugs fixed in https://github.com/tsitu/MH-Tools/commit/0c5e1f3c0fbf53879bccd470ee6bed34e18fad01 by removing loadedParams and adding a CRE_USER check respectively.
_Side effect:_ Changing locations will now prioritize cheese/charms specified in the URL.

Feel free to close if you feel this is sufficiently resolved!

**Comment by Babalela01** [comment]
Awesome, glad you had a look at it 😀
