### ISSUE TITLE
Moussu Picchu

### ISSUE THREAD

**Issue by groupsky** [tsitu/MH-Tools#45]
I started integrating the MoPi population and mice powers. Will open PR soon, until then just want to notify so in case anybody is working on this, we can consolidate.

Population for Low/Low is based on horntracker, the rest comes from [this forum thread](https://www.mousehuntgame.com/forum/showthread.php?132057-Moussu-Picchu-Mouse-Powers-and-Minimum-Luck).

**Comment by tsitu** [comment]
Haven't gotten too far with preparing MoPi and BWRift populations, so I'm excited to see what you've got.

Moving forward, I think it will be crucial for us to query [Jack's Tools](https://mhhunthelper.agiletravels.com/tracker.php) in addition to/instead of HT. He pushes [snapshots](https://github.com/DevJackSmith/mh-hunt-helper/commits/dev) of his SQL DB regularly and is extremely active on the forums, Facebook, and Discord.

One major reason for this is that we need accurate tracking of location phases/stages (especially so for new areas) in order for the data to be usable. Jack already has Rain/Wind levels implemented ([Cycloness example](https://mhhunthelper.agiletravels.com/?mouse=764)) and reasonable sample sizes.

**Comment by tsitu** [comment]
Added in ac209dafdf2fcdc93d47cfff4d8c0bc981c73868

We can reopen this issue or create new ones if there are any bugs.
