### ISSUE TITLE
Bonus power

### ISSUE THREAD

**Issue by groupsky** [tsitu/MH-Tools#47]
Similar to bonus luck, a field to enter bonus power. Current use for Halloween aura, in future may be used for some special charms, or whatever.

Should be straightforward to implement, similar to the way ZT weapons are handled.

An issue would be to automatically determine the value from submitted trap power. Haven't sit down to do the math, but it may be necessary to compute it in the bookmarlet using the power value tooltip values. This could also interfere with the FRift battery handling.

**Comment by tsitu** [comment]
This would be useful, but now that the devs have introduced an aura bonus for something other than luck, what's keeping future auras from affecting cheese effect, attraction bonus, or even trap type? Bonus fields for those attributes _could_ definitely be added but that might introduce clutter and new bugs to the already elongated UI.

State management is currently quite hacky if not nonexistent (plus there are 0 tests), which is a byproduct of me rapidly iterating on haoala's original code before learning JS best practices. @Babalela01 and I have been brainstorming a redesign/rewrite of the core [here](https://docs.google.com/document/d/1C0U257sWu4xal3RF6iHYtncIuKEhiuuRsrbCKEkNF9I/edit?usp=sharing) which could make the process of implementing new components more stable and simple.

In the meantime, I think the "Custom values" checkbox is sufficient, especially since the aura will expire in a month.

**Comment by groupsky** [comment]
For the moment, I don't plan on implementing it and my quick dig into the code showed it's not straightforward, so it seems the benefit is not worth the effort.
